---
# handlers file for ca_certificates
- name: Update CA certificates
  ansible.builtin.command:
    argv:
      - /usr/sbin/update-ca-certificates
  changed_when: true
  become: true
  become_user: root
